/**
 * Content Claude Code injects into the USER role is not a prompt.
 *
 * Invoking a Skill writes the skill's whole body into the transcript as a
 * `type: "user"` entry. It became prompt #3 of a 2-prompt session, and the
 * damage was not cosmetic — measured on prod session 92e45049:
 *
 *   idx 0  real prompt   commit 8731a444   +73 -4
 *   idx 1  real prompt   commit null       +100 -1
 *   idx 2  SKILL BODY    commit null       +100 -1   <- turn 1's diff, again
 *   idx 3  real prompt   commit null       +20  -0
 *
 * The phantom opened mid-way through the real turn, so that turn's work was
 * duplicated onto both rows and its commit was left attached to no turn at
 * all — which is why the page hung both commits off idx 0, the only turn that
 * still had one.
 *
 * #1136 fixed the TAGGED half of this (`<system-reminder>`, `<task-notification>`)
 * in `cleanPrompt` and recorded the prediction that "the injected-message
 * vocabulary grows over time". It grew, and this time there is no tag to grow
 * into: a skill body is ordinary markdown. `isMeta` is the structural signal,
 * and nothing in the CLI read it.
 *
 * The two mechanisms are complementary, not redundant — `<task-notification>`
 * entries carry `isMeta: false`, so cleanPrompt is still what handles those.
 */
import { describe, it, expect } from 'vitest';
import fs from 'fs';
import os from 'os';
import path from 'path';
import { parseTranscript, extractPromptFileMappings } from '../transcript.js';

function writeTranscript(rows: any[]): string {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'origin-meta-'));
  const p = path.join(dir, 'session.jsonl');
  fs.writeFileSync(p, rows.map((r) => JSON.stringify(r)).join('\n') + '\n');
  return p;
}

const user = (text: string, extra: Record<string, unknown> = {}) => ({
  type: 'user', timestamp: '2026-08-30T13:00:00.000Z',
  message: { role: 'user', content: text }, ...extra,
});
const assistant = (id: string, out: number) => ({
  type: 'assistant', timestamp: '2026-08-30T13:00:01.000Z',
  message: { id, role: 'assistant', model: 'claude-opus-5', content: [{ type: 'text', text: 'ok' }],
    usage: { input_tokens: 1, output_tokens: out, cache_read_input_tokens: 0, cache_creation_input_tokens: 0 } },
});
// A skill body as Claude Code actually writes it: text BLOCK, isMeta true.
const skillBody = {
  type: 'user', timestamp: '2026-08-30T13:00:02.000Z', isMeta: true,
  message: { role: 'user', content: [{ type: 'text', text: 'Base directory for this skill: /tmp/skills/claude-api\n\n# Building LLM-Powered Applications\n\nlots of markdown' }] },
};

describe('agent-injected user-role content', () => {
  it('does not count a Skill body as a prompt', () => {
    const p = writeTranscript([
      user('first real prompt'), assistant('m1', 10),
      skillBody, assistant('m2', 10),
      user('second real prompt'), assistant('m3', 10),
    ]);
    expect(parseTranscript(p).prompts).toEqual(['first real prompt', 'second real prompt']);
  });

  it('keeps the real prompt at its own index — the phantom shifted everything after it', () => {
    // This is the whole harm. A phantom at idx 1 pushes the second real
    // prompt to idx 2, and every capture keyed by promptIndex lands on the
    // wrong row from there on.
    const p = writeTranscript([
      user('first real prompt'), assistant('m1', 10),
      skillBody, assistant('m2', 10),
      user('second real prompt'), assistant('m3', 10),
    ]);
    const maps = extractPromptFileMappings(p);
    expect(maps.map((m) => m.promptIndex)).toEqual([0, 1]);
    expect(maps[1].promptText).toBe('second real prompt');
  });

  it('agrees with parseTranscript on the count — the invariant #1136 was about', () => {
    // Two independent implementations of "is this a user prompt" drifting is
    // what produced 6-prompts-vs-18-captures. They must move together.
    const p = writeTranscript([
      user('one'), assistant('m1', 10),
      skillBody, assistant('m2', 10),
      user('two'), assistant('m3', 10),
      skillBody, assistant('m4', 10),
      user('three'), assistant('m5', 10),
    ]);
    expect(parseTranscript(p).prompts.length).toBe(extractPromptFileMappings(p).length);
    expect(parseTranscript(p).prompts.length).toBe(3);
  });

  it('drops the other things Claude Code flags as meta', () => {
    // All observed across local transcripts: resume injection, slash-command
    // expansion, cross-session message, local-command caveat. Each FOLLOWS the
    // real prompt that caused it, so dropping them orphans no turn.
    const metas = [
      'Continue from where you left off.',
      'Review target: `1074`  `minimal prompt -> single careful diff pass`',
      'Another Claude session sent a message: <cross-session>hi</cross-session>',
      '<local-command-caveat>Caveat: The messages below were generated by...</local-command-caveat>',
    ];
    const p = writeTranscript([
      user('the real ask'), assistant('m1', 10),
      ...metas.flatMap((t, i) => [user(t, { isMeta: true }), assistant(`x${i}`, 5)]),
    ]);
    expect(parseTranscript(p).prompts).toEqual(['the real ask']);
  });

  it('still counts a normal prompt that merely LOOKS injected', () => {
    // The guard is the flag, not the text. A user may legitimately paste
    // skill-ish prose, and isMeta is absent on anything they typed.
    const p = writeTranscript([
      user('Base directory for this skill: /tmp/x — why does this show up as a prompt?'),
      assistant('m1', 10),
    ]);
    expect(parseTranscript(p).prompts.length).toBe(1);
  });

  it('leaves the tagged envelopes to cleanPrompt — they are NOT flagged meta', () => {
    // `<task-notification>` arrives with isMeta false/absent, so the #1136
    // text-level rule is still the thing that handles it. Removing either
    // mechanism reopens half the bug.
    const p = writeTranscript([
      user('real one'), assistant('m1', 10),
      user('<task-notification><task-id>abc</task-id></task-notification>'), assistant('m2', 10),
    ]);
    expect(parseTranscript(p).prompts).toEqual(['real one']);
  });
});
