/**
 * A slash command's transcript footprint is not a prompt, and neither is an
 * interrupt. `/model` leaves three user entries; only the caveat is flagged
 * isMeta, and only `<command-name>` was stripped — so "<command-message>model"
 * and "Set model to …" became turns 2 and 3 of prod vodka a219d616, the hook
 * side's turn 5 mapped onto row 4, and row 7 doubled its work.
 */
import { describe, it, expect } from 'vitest';
import fs from 'fs';
import os from 'os';
import path from 'path';
import { cleanPrompt, parseTranscript } from '../transcript.js';

const entry = (text: string, extra: Record<string, unknown> = {}) =>
  JSON.stringify({ type: 'user', timestamp: '2026-09-03T13:53:49.000Z', message: { role: 'user', content: [{ type: 'text', text }] }, ...extra });

describe('cleanPrompt drops what nobody typed', () => {
  it('the slash command and its output', () => {
    expect(cleanPrompt('<command-name>/model</command-name>\n            <command-message>model</command-message>\n            <command-args></command-args>')).toBeNull();
    expect(cleanPrompt('<local-command-stdout>Set model to `claude-opus-5`</local-command-stdout>')).toBeNull();
    expect(cleanPrompt('<local-command-caveat>Caveat: generated by the user while running local commands</local-command-caveat>')).toBeNull();
  });
  it('the interrupt marker', () => {
    expect(cleanPrompt('[Request interrupted by user]')).toBeNull();
    expect(cleanPrompt('[Request interrupted by user for tool use]')).toBeNull();
  });
  it('but keeps a real prompt that merely mentions a command', () => {
    expect(cleanPrompt('run /model and tell me what it says')).toBe('run /model and tell me what it says');
    expect(cleanPrompt('Try again')).toBe('Try again');
  });
});

describe('parseTranscript numbers only real prompts', () => {
  it('a /model in the middle does not add turns', () => {
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'origin-lc-'));
    const p = path.join(dir, 't.jsonl');
    fs.writeFileSync(p, [
      entry('generate some nice code for this repo'),
      entry('Try again'),
      entry('<local-command-caveat>Caveat: …</local-command-caveat>', { isMeta: true }),
      entry('<command-name>/model</command-name>\n            <command-message>model</command-message>\n            <command-args></command-args>'),
      entry('<local-command-stdout>Set model to `claude-opus-5`</local-command-stdout>'),
      entry('Try again'),
      entry('[Request interrupted by user]'),
      entry('generate some nice code for this repo'),
      entry('Try again'),
    ].join('\n') + '\n');
    const parsed = parseTranscript(p);
    expect(parsed.prompts).toEqual([
      'generate some nice code for this repo', 'Try again', 'Try again',
      'generate some nice code for this repo', 'Try again',
    ]);
  });
});
