import {
  loadSessionState,
  saveSessionState,
  findSessionByClaudeId,
  type SessionState,
  type TabCompletionStats,
} from './session-state.js';

// ─── Public API ────────────────────────────────────────────────────────────

/**
 * Record an AI tab/inline completion event.
 * Increments counters in the session state's tabCompletions field.
 *
 * @param sessionTag - Session tag or Claude session ID to find the session
 * @param chars - Number of characters generated by the completion
 * @param accepted - Whether the user accepted the completion
 * @param cwd - Working directory for session lookup
 */
export function recordTabCompletion(
  sessionTag: string,
  chars: number,
  accepted: boolean,
  cwd?: string,
): void {
  // Find the session by tag or Claude session ID
  let state: SessionState | null = null;
  state = loadSessionState(cwd, sessionTag);
  if (!state) {
    state = findSessionByClaudeId(sessionTag, cwd);
  }
  if (!state) return;

  // Initialize tab completion stats if not present
  if (!state.tabCompletions) {
    state.tabCompletions = {
      count: 0,
      acceptedCount: 0,
      totalCharsGenerated: 0,
      avgAcceptanceRate: 0,
    };
  }

  // Update counters
  state.tabCompletions.count++;
  state.tabCompletions.totalCharsGenerated += chars;
  if (accepted) {
    state.tabCompletions.acceptedCount++;
  }

  // Recalculate acceptance rate
  state.tabCompletions.avgAcceptanceRate = state.tabCompletions.count > 0
    ? Math.round((state.tabCompletions.acceptedCount / state.tabCompletions.count) * 100) / 100
    : 0;

  // Persist
  saveSessionState(state, cwd, sessionTag);
}

/**
 * Get tab completion statistics for a session.
 *
 * @param sessionTag - Session tag or Claude session ID
 * @param cwd - Working directory for session lookup
 * @returns TabCompletionStats or null if session not found or no completions recorded
 */
export function getTabCompletionStats(
  sessionTag: string,
  cwd?: string,
): TabCompletionStats | null {
  let state: SessionState | null = null;
  state = loadSessionState(cwd, sessionTag);
  if (!state) {
    state = findSessionByClaudeId(sessionTag, cwd);
  }
  if (!state) return null;

  return state.tabCompletions || null;
}

/**
 * Format tab completion stats for display.
 */
export function formatTabCompletionStats(stats: TabCompletionStats): string {
  const lines: string[] = [
    `Tab Completions: ${stats.count}`,
    `  Accepted:      ${stats.acceptedCount} (${Math.round(stats.avgAcceptanceRate * 100)}%)`,
    `  Total Chars:   ${stats.totalCharsGenerated.toLocaleString()}`,
  ];

  return lines.join('\n');
}

/**
 * Process a PostToolUse event that may be a tab completion.
 * Called from hooks.ts when processing Cursor/Windsurf events.
 *
 * @param input - Hook input data
 * @param cwd - Working directory
 */
export function handleTabCompletionEvent(
  input: Record<string, any>,
  cwd?: string,
): void {
  // Check if this is a completion event (Cursor/Windsurf-specific)
  const toolName = input.tool_name || input.toolName || '';
  const isCompletion = toolName.toLowerCase().includes('completion') ||
    toolName.toLowerCase().includes('inline') ||
    toolName.toLowerCase().includes('autocomplete');

  if (!isCompletion) return;

  const sessionId = input.session_id || '';
  const chars = input.chars || input.characters || input.length || 0;
  const accepted = input.accepted !== false; // Default to accepted

  if (sessionId && chars > 0) {
    recordTabCompletion(sessionId, chars, accepted, cwd);
  }
}
